name: Deploy to Azure
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ azureSecrets.DOCKER_HUB_USERNAME }}
          password: ${{ azureSecrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{azureSecrets.DOCKER_HUB_USERNAME }}/devops:latest,${{ azureSecrets.DOCKER_HUB_USERNAME }}/devops:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-dhbw-devops'
          slot-name: 'production'
          publish-profile: ${{azureSecrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          images: ${{ azureSecrets.DOCKER_HUB_USERNAME }}/devops:${{ github.sha }}